version: "3.8"
services:
  db:
    image: postgres:16.2
    container_name: postgresdb
    ports:
      - 5431:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - "$PWD/ConvertaApi/.postgres.env.example"

  converta-api:
    build:
      context: ./ConvertaApi
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8080:8080
    env_file:
      - "$PWD/ConvertaApi/.env.example"
    depends_on:
      - db

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
      target: development
    container_name: api-gateway
    ports:
      - 3000:3000
    volumes:
      - ./ApiGateway:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - "$PWD/ApiGateway/.env.example"
    depends_on:
      - converta-api

volumes:
  postgres-data:
