version: "3.8"
services:
  postgresdb:
    image: postgres:16.2
    ports:
      - 5431:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - converta-network
    env_file:
      - "$PWD/ConvertaApi/.postgres.env"

  converta-api:
    image: oraio/converta-api:latest
    ports:
      - 8080:8080
    networks:
      - converta-network
    env_file:
      - "$PWD/ConvertaApi/.env"

  api-gateway:
    image: oraio/converta-api-gateway:latest
    ports:
      - 80:3000
    networks:
      - converta-network
    volumes:
      - ./ApiGateway:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - "$PWD/ApiGateway/.env"

volumes:
  postgres-data:

networks:
  converta-network:
    name: converta-network
    external: true
