apiVersion: v1
kind: Service
metadata:
  name: converta-service
spec:
  selector:
    app: converta
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 5432
      targetPort: 5432
